services:
  # web:
  #   container_name: proximity_web_ui
  #   build: docker/web.Dockerfile
  #   command: python manage.py runserver
  backend:
    container_name: proximity_web_backend
    build:
      context: .
      dockerfile: docker/dockerfiles/backend/Dockerfile
    depends_on:
      - postgis
      - search
      - cache
  postgis:
    container_name: proximity_search_postgis
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGIS_DB: spatial_db_postgis
      POSTGIS_USER: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgis_data:/var/lib/postgresql_postgis/data
    command: sh -c "psql -U ${POSTGRES_USER} -d spatial_db_postgis -c 'CREATE EXTENSION postgis;' && psql -U ${POSTGRES_USER} -d spatial_db_postgis -c 'CREATE EXTENSION postgis_topology;'"

  search:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  cache:
    container_name: redis
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"

volumes:
  postgis_data:
